### PR TITLE
Add pageSize as an optional additional document option

### PR DESCRIPTION
**Pull request by juralio-james**
Enhancement to allow the user to add a custom pageSize parameter to generate non U.S. letter size documents.
Based off of  #60 but without the breaking change, as the existing default height and width options are applied if no pageSize options are supplied

### CODE REVIEW

**Comment by privateOmega** [comment]
@juralio-james Sorry for seeing this so late, but could you please set it to target develop instead of master?

**Comment by juralio-james** [comment]
@privateOmega no problem, that should be it updated now

**Comment by privateOmega** [comment]
cleaned it up and merge it as https://github.com/privateOmega/html-to-docx/pull/161

**Comment by privateOmega** [comment]
@juralio-james Thanks for this changeset and I apologize for the delay.

**Comment by juralio-james** [comment]
@privateOmega Thank you for cleaning it up! Totally fell off my radar

**Pull request closed without merging**
