### PR TITLE
fix: add typescript definition

### LINKED ISSUE #79: @Types
`declare module 'html-to-docx'
{
    interface Margins
    {
        /**
         * top <Number> distance between the top of the text margins for the main document and the top of the page for all pages in this section in TWIP.
         * Defaults to 1440. Supports equivalent measurement in pixel, cm or inch.
         */
        top: number;

        /**
         * right <Number> distance between the right edge of the page and the right edge of the text extents for this document in TWIP.
         * Defaults to 1800. Supports equivalent measurement in pixel, cm or inch.
         */
        right: number;

        /**
         * bottom <Number> distance between the bottom of text margins for the document and the bottom of the page in TWIP.
         * Defaults to 1440. Supports equivalent measurement in pixel, cm or inch.
         */
        bottom: number;

        /**
         * left <Number> distance between the left edge of the page and the left edge of the text extents for this document in TWIP.
         * Defaults to 1800. Supports equivalent measurement in pixel, cm or inch.
         */
        left: number;

        /**
         * header <Number> distance from the top edge of the page to the top edge of the header in TWIP.
         * Defaults to 720. Supports equivalent measurement in pixel, cm or inch.
         */
        header: number;

        /**
         * footer <Number> distance from the bottom edge of the page to the bottom edge of the footer in TWIP.
         * Defaults to 720. Supports equivalent measurement in pixel, cm or inch.
         */
        footer: number;

        /**
         * gutter <Number> amount of extra space added to the specified margin, above any existing margin values. This setting is typically used when a document is being created for binding in TWIP.
         * Defaults to 0. Supports equivalent measurement in pixel, cm or inch.
         */
        gutter: number;
    }

    interface Row
    {
        /**
         * cantSplit <?Boolean> flag to allow table row to split across pages. Defaults to false.
         */
        cantSplit?: boolean;
    }

    interface Table
    {
        row?: Row;
    }

    export interface DocumentOptions
    {
        /**
         * orientation <"portrait"|"landscape"> defines the general orientation of the document. Defaults to portrait.
         */
        orientation?: "portrait" | "landscape";

        margins?: Margins

        /**
         * title <?String> title of the document.
         */
        title?: string;

        /**
         * subject <?String> subject of the document.
         */
        subject?: string;

        /**
         * creator <?String> creator of the document. Defaults to html-to-docx
         */
        creator?: string;

        /**
         * keywords <?Array<String>> keywords associated with the document. Defaults to ['html-to-docx'].
         */
        keywords?: string[];

        /**
         * description <?String> description of the document.
         */
        description?: string;

        /**
         * lastModifiedBy <?String> last modifier of the document. Defaults to html-to-docx.
         */
        lastModifiedBy?: string;

        /**
         * revision <?Number> revision of the document. Defaults to 1.
         */
        revision?: number;

        /**
         * createdAt <?Date> time of creation of the document. Defaults to current time.
         */
        createdAt?: Date;

        /**
         * modifiedAt <?Date> time of last modification of the document. Defaults to current time.
         */
        modifiedAt?: Date;

        /**
         * headerType <"default"|"first"|"even"> type of header. Defaults to default.
         */
        headerType?: "default" | "first" | "even";

        /**
         * header <?Boolean> flag to enable header. Defaults to false.
         */
        header?: boolean;

        /**
         * footerType <"default"|"first"|"even"> type of footer. Defaults to default.
         */
        footerType?: "default" | "first" | "even";

        /**
         * footer <?Boolean> flag to enable footer. Defaults to false.
         */
        footer?: boolean;

        /**
         * font <?String> font name to be used. Defaults to Times New Roman.
         */
        font?: string;

        /**
         * fontSize <?Number> size of font in HIP(Half of point). Defaults to 22. Supports equivalent measure in pt.
         */
        fontSize?: number;

        /**
         * complexScriptFontSize <?Number> size of complex script font in HIP(Half of point). Defaults to 22. Supports equivalent measure in pt.
         */
        complexScriptFontSize?: number;

        table?: Table;

        /**
         * pageNumber <?Boolean> flag to enable page number in footer. Defaults to false. Page number works only if footer flag is set as true.
         */
        pageNumber?: boolean;

        /**
         * skipFirstHeaderFooter <?Boolean> flag to skip first page header and footer. Defaults to false.
         */
        skipFirstHeaderFooter?: boolean;
    }

    /**
     * @param htmlString <String> clean html string equivalent of document content.
     * @param headerHTMLString <String> clean html string equivalent of header. Defaults to <p></p> if header flag is true.
     * @param documentOptions <DocumentOptions>
     * @param footerHTMLString <String> clean html string equivalent of footer. Defaults to <p></p> if footer flag is true.
     * @constructor
     * @private
     */
   export default function HTMLtoDOCX(htmlString: string, headerHTMLString: string, documentOptions: DocumentOptions, footerHTMLString?: string): Promise<Buffer | Blob>;
}`

### PR DESCRIPTION
**Pull request by adrum**
Resolves #79

### CODE REVIEW

**Comment by privateOmega** [comment]
@adrum I finally had the time to review this PR and good job on this, the only concern I have is you have missed out on `lineNumber` and `lineNumberOptions` typings. Could you please add those as well, and then I will immediately merge them?

**Comment by tasola** [comment]
Is this PR still relevant? Seems like there's not so much more left to do before merging, or is `lineNumberOptions` complex? I've just started looking into this project, and I'd love to use it with ts

**Comment by privateOmega** [comment]
@adrum @tasola  Could either of you review this quickly? I am no expert in typescript, but I have tried to add as much typing as I could. Also I have incorporated this PRs content as well, this way the entire repository would be migrated to typescript, not just the public interface.

**Comment by Napokue** [comment]
@privateOmega I am continuing on your PR on my fork to correctly implement a typescript approach, if you are okay with that. Wouldn't be perfect as first version, but we can move forward from then. I really would like to revitalize this package to modern standards!

I already am able to correct emit the typescript files and the associated type definition files via rollup. Question: is there a reason to emit two different index files? The `html-to-docx.esm.js` and `html-to-docx.umd.js` files.

Sidenote: I have migrated to rollup 3.0 (will update to the newest version when the PR is ready).

**Comment by privateOmega** [comment]
@Napokue Thats great news and I dont mind one bit, in fact I am happy that someone can contribute to this project while I cannot. Sounds good.

ESM is for latest ecmascript module bundlers and UMD is a replacement for CJS and  AMD, hence should work both in frontend and backend projects. Lets go with those for now.

I was thinking of moving away from rollup to webpack, since I always had some issue or the other with rollup bundles, as evident by some issues raised in this project, but we can take it up as a different effort anyways, lets stick with only TS changes in here.

**Comment by Timo-DK** [comment]
Unfortunately due to limited time I am not able to contribute to this at the moment. Hopefully someone else will take it upon them!

**Comment by chriscarrollsmith** [comment]
You need to allow null argument values where appropriate in the export statement, e.g.:

headerHTMLString: string | null

**Comment by adrum** [comment]
I'm going to close this in favor of https://github.com/privateOmega/html-to-docx/pull/157 . Converting to TypeScript is probably the best way to go in the long run.

**Pull request closed without merging**
