### PR TITLE
feat(font-family): use the first element as the font name and the last a generic font name

### PR DESCRIPTION
**Pull request by erenard**
Hello,

### Goal of this PR
- extract the font information from the CSS `font-family`,
- insert the font in the text using `rFonts` in the `document.xml`
- register the used fonts in `fontTable.xml`, hinting the client about the font style if it doesn't have it installed.

### CSS to DOCX font mapping
Given the following CSS: `font-family: MyFont, Font1, Font2, serif`:
- `MyFont` will be the font name,
- `Font1, Font2` will be ignored,
- `serif` will be used to extract font properties.

### generic font names
The three main generic font names are translated to font properties:
#### serif
```
<w:font w:name="MyFont">
    <w:altName w:val="Times New Roman"/>
    <w:family w:val="roman"/>
    <w:pitch w:val="variable"/>
</w:font>
```
#### sans-serif
```
<w:font w:name="MyFont">
    <w:altName w:val="Arial"/>
    <w:family w:val="swiss"/>
    <w:pitch w:val="variable"/>
</w:font>
```
#### monospace
```
<w:font w:name="MyFont">
    <w:altName w:val="Courier New"/>
    <w:family w:val="modern"/>
    <w:pitch w:val="fixed"/>
</w:font>
```

Results really depends on the Word client:
- `Word Desktop` work as intended,
- `LibreOffice` ignore the `fontTable.xml` file, and find a font by itself
- `Word Online` ignore the `fontTable.xml` file, and find a font by itself but, since he is packed with a lot of fonts, find the wanted font *most of the time*.

### CODE REVIEW

**Comment by privateOmega** [comment]
@erenard Could you please cherry-pick these changes onto develop?

**Comment by drawmoon** [comment]
Very nice feature, but I accidentally found that it doesn't seem to work with Chinese. 😊

**Comment by nicolasiscoding** [comment]
Hey @erenard this is quiet useful! Can you rebase with develop? Maybe I can QA it and get it merged

**Comment by erenard** [comment]
Hello, the rebase is done.

**Pull request closed without merging**
