### PR TITLE
fix: upgrade xmlbuilder2 to solve unhandled rejection error

### PR DESCRIPTION
**Pull request by zedtux**
This PR fixes the error reported from issue #92.

After having found [this issue from the xmlbuilder2 library](https://github.com/oozcitak/xmlbuilder2/issues/23), I tried to update the (quite) old version of `xmlbuilder2` this package use and the `.docx` generation now work in my project !

### CODE REVIEW

**Comment by privateOmega** [comment]
@zedtux TYSM for this PR. I know this has been a headache for a couple of users, would really like to merge this PR in ASAP, but before that could you please change your base branch to develop, and target to develop as well?

**Comment by zedtux** [comment]
Done. 

You should set the `develop` branch as the default one if it is. I got my PR pointing `master` since it is the default branch.

**Comment by privateOmega** [comment]
> Done.
> 
> You should set the `develop` branch as the default one if it is. I got my PR pointing `master` since it is the default branch.

Thanks, that was intentional since, sometimes there would be some time difference between when a PR lands on develop branch and when I do a release, and develop is a branch I dont mind having in a broken state.

**Comment by zedtux** [comment]
I see, but then it leads to the mistake I did.

**Comment by privateOmega** [comment]
@zedtux Funstuff, I just remembered why I hard fixed xmlbuilder2 version to 2.1.2, xmlbuilder2 v2.1.3 introduces a bug which makes the generated docx unusable.

image

So if you notice the wp:inline somehow changed to w:inline which is not supposed to be.

I just triaged it, and it seems to be introduced by a fix for https://github.com/oozcitak/xmlbuilder2/issues/18. So I will be reverting your changes.

**Comment by privateOmega** [comment]
https://github.com/privateOmega/html-to-docx/pull/171 Raised and merged this now to solve the "unhandled rejection error" by forcing the respective transitive deps, and not updating xmlbuilder2 to the buggy versions.

**Comment by zedtux** [comment]
@privateOmega It doesn't work with version 1.6.2 :

```
Uncaught (in promise) TypeError: Cannot call a class as a function
    _classCallCheck NodeImpl.js:11
    NodeImpl NodeImpl.js:66
    _createSuperInternal DocumentImpl.js:29
    DocumentImpl DocumentImpl.js:80
    ...
```

**Comment by zedtux** [comment]
Also, your sticking to a very old version of xmlbuilder2. Could you please check newer versions ?

**Comment by privateOmega** [comment]
@zedtux its supposed to be 1.6.3, not 1.6.2. Well I tried with multiple versions of xmlbuilder including latest, but it breaks the image feature which I cannot allow. I have posted a comment in xmlbuilder2 to know if there;s a workaround, if yes I will upgrade it for sure.

**Comment by nsantini** [comment]
@privateOmega this still doesn't work on version 1.6.5 :(

**Pull request merged**
