### PR TITLE
Feature/browser example

### LINKED ISSUE #3: Will this project work in browser?
Searched NPM and found this project. Tried in browser but gives me error about fs. Is this project for node only or I miss some settings...

### PR DESCRIPTION
**Pull request by privateOmega**
Switch from CJS to UMD build for browser support as well along with support for node.js
Switched out Crypto with ShortID
Replaced html-minifier package with custom regex solution.

fix #3

### CODE REVIEW

**Comment by amarksnightwatch** [comment]
I'm also interested in using in browser. Are you releasing a new npm version soon?

**Comment by privateOmega** [comment]
@amrita-syn my bad, I never tried the umd build via script tag on browser, but on React. I will try this out ASAP.

**Comment by wnabil** [comment]
@privateOmega any news when this will be released ?

**Comment by amilich** [comment]
Any plans to release soon?

**Comment by privateOmega** [comment]
@amrita-syn could you please test this with react and if all looks good, lets approve and merge it, since there's like so much demand. I am unable to get it working with browser's umd build due to lack of js module system knowledge. I will add a disclaimer in the README, saying it won't work with browser rightaway if there's no bundler present to resolve dependencies.

**Comment by amrita-syn** [comment]
Sure, we can pick that piece up later.
Regards,
Amrita

**Review by amrita-syn — APPROVED** [review]
Looks fine.

**Comment by privateOmega** [comment]
Released a new version which contains this PR. So finally we have browser support :D

**Pull request merged**
