### PR TITLE
Feature/skip first header

### PR DESCRIPTION
**Pull request by privateOmega**
PR to skip header and footer in first page only.

### CODE REVIEW

**Review by amrita-syn — CHANGES_REQUESTED** [review]
Looks like what we are doing is marking the first page as title page instead of `skip`ing for page 1.

I would rather call the flag `titlePage` and mention in documentation that the title page gets a blank header/footer since first page header is not defined. This would also make it independent of header and footer being specified.

**Comment by mahendra119** [comment]
Hello @privateOmega @amrita-syn 
First of all, it is a great package but I ran into one issue when I am setting headerType to "First or even", it is not working at all. It only works when set to "default" option. Also is there any setting where we can skip header/footer on the first page or show different header/footer on first page.
I have installed this package and it contains file in minified version so I am not able to find the code that you have added in PR.

Any help would be appreciated. Thanks

**Comment by privateOmega** [comment]
@amrita-syn Since it essentially skips first page's header and footer, I cannot think of a better name than the one assigned. **titlePage** as a flag doesn't really convey the meaning of it for me. I suggest, we can merge it if it works for now and we can come up with a different name in the future.

**Comment by privateOmega** [comment]
@mahendra119 I haven't tested out even and odd options of it, to be honest I don't even remember if I had ever added support for it.

Yes this PR when merged would allow you to have that option until its merged. If you want to try it out before its deployed, try installing this git branch.

**Comment by mahendra119** [comment]
Hello @privateOmega ,
Thanks for the response. When are you planning to publish a new version?
Actually, it is not working for me. I hope after installing the new version, it will work for me.

Thanks

**Review by amrita-syn — APPROVED** [review]

**Pull request merged**
